### ISSUE TITLE
cookie求助

### ISSUE THREAD

**Issue by xiaoqi2020** [h141242/jingyi#2]
请问老板，直接抓取的cookie不能用，是要删减吗？

**Comment by xiaoqi2020** [comment]
我抓出来的是这样的


lDlk_ecc9_saltkey=H28IQYYj; lDlk_ecc9_lastvisit=16735658; lDlk_ecc9_con_request_uri=http%3A%2F%2Fbbs.125.la%2Fconnect.php%3Fmod%3Dlogin%26op%3Dcallback%26referer%3Dindex.php; lDlk_ecc9_client_token=4531B8598162AC7EF9109EE2D3F3E; lDlk_ecc9_connect_login=1; lDlk_ecc9_connect_is_bind=1; lDlk_ecc9_connect_uin=4531B98162AC7EF9109EE2D3D42F3E; lDlk_ecc9_nofavfid=1; lDlk_ecc9_creditnotice=0D0D0D0DD0D0D93370; lDlk_ecc9_creditbase=0D0D08D0D0D0D0; lDlk_ecc9_visitedfid=81; lDlk_ecc9_viewid=tid_14759063; lDlk_ecc9_st_p=93370%7C16738%7C459fa40369388ac6c4c27fc00c92378b; lDlk_ecc9_home_diymode=1; Hm_lvt_fa32dadde3745af309b587b38d20ea1d=1673746030; Hm_lpvt_fa32dadde3745af309b587b38d20ea1d=1673746030; lDlk_ecc9_client_created=1673746036; lDlk_ecc9_ulastactivity=bd8dBA7nlPV1vF%2BxYDxCpPVeVlHYlrb3as6jYCifb8vMMd1FVQH9; lDlk_ecc9_auth=99ff9VVqNIzZ6RCJkoNfxEA1U4cUovjrxFBHXwEuJYTJmcARBcTv6eA%2BXUFkLsVSY0p0wna3ADLcJybOAkderi5I%2Bg; lDlk_ecc9_stats_qc_login=3; lDlk_ecc9_sid=FH9Bkd; lDlk_ecc9_lip=222.209.160.123%2C1673746036; lDlk_ecc9_lastact=16737478%09forum.php%09; lDlk_ecc9_onlineusernum=4009

**Comment by xiaoqi2020** [comment]
我搞定了

**Comment by h141242** [comment]
不用删减




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月15日(星期天) 上午9:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [h141242/jingyi] cookie求助 (Issue #2)





 
请问老板，直接抓取的cookie不能用，是要删减吗？
